<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38785" started-at="2019-01-20T05:28:25Z" finished-at="2019-01-20T05:29:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38785" started-at="2019-01-20T05:28:25Z" finished-at="2019-01-20T05:29:04Z">
      <class name="MavenTest.com.MavenProject.AppTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:MavenTest.com.MavenProject.AppTest@46d56d67]" name="setUp" is-config="true" duration-ms="4501" started-at="2019-01-20T10:58:25Z" finished-at="2019-01-20T10:58:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyCNNLinks()[pri:0, instance:MavenTest.com.MavenProject.AppTest@46d56d67]" name="verifyCNNLinks" duration-ms="25477" started-at="2019-01-20T10:58:30Z" finished-at="2019-01-20T10:58:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCNNLinks -->
        <test-method status="FAIL" signature="verifyShopingCard()[pri:0, instance:MavenTest.com.MavenProject.AppTest@46d56d67]" name="verifyShopingCard" duration-ms="7866" started-at="2019-01-20T10:58:55Z" finished-at="2019-01-20T10:59:03Z">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<Test[1]> but was:<Test[2]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<Test[1]> but was:<Test[2]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at MavenTest.com.MavenProject.AppTest.verifyShopingCard(AppTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyShopingCard -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:MavenTest.com.MavenProject.AppTest@46d56d67]" name="quitBrowser" is-config="true" duration-ms="892" started-at="2019-01-20T10:59:03Z" finished-at="2019-01-20T10:59:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- MavenTest.com.MavenProject.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
